<?php
declare(strict_types=1);

return [
    'contact' => [
        'address' => '26-28 rue de Londres, 75009 Paris',
        'phone' => 'A completer',
        'email' => 'A completer',
        'hours' => 'Sur rendez-vous',
    ],
    'formations' => [
        [
            'slug' => 'francais-professionnel',
            'title' => 'Francais professionnel',
            'category' => 'Francais',
            'summary' => 'Communiquer efficacement a l oral et a l ecrit en contexte de travail, avec preparation a la certification LEVELTEL.',
            'duration' => '50 heures',
            'level' => 'A2+ a C1',
            'price' => '2500 EUR TTC en inter, tarif modulable en intra',
            'certification' => 'LEVELTEL',
            'location' => '26-28 rue de Londres, 75009 Paris',
            'format' => 'Presentiel, distanciel ou hybride selon le parcours',
            'funding' => 'CPF, OPCO, entreprise ou particulier selon eligibilite',
            'objectives' => [
                'Comprendre des echanges oraux en contexte professionnel.',
                'Prendre la parole lors de situations de travail.',
                'Lire et analyser des documents professionnels.',
                'Rediger des e-mails, notes, comptes rendus et supports simples.',
                'Se preparer a une certification linguistique reconnue.',
            ],
            'audience' => 'Salaries, independants, demandeurs d emploi et entreprises souhaitant renforcer le francais professionnel.',
            'requirements' => 'Test de positionnement obligatoire. Niveau minimum recommande : A2+.',
            'access' => 'Entrees et sorties permanentes selon calendrier et validation du positionnement. Delai indicatif : 1 a 3 semaines.',
            'accessibility' => 'Les besoins specifiques et situations de handicap sont etudies au moment de la demande.',
            'program' => [
                'Diagnostic initial et definition des objectifs.',
                'Expression orale en situation professionnelle.',
                'Compréhension ecrite et orale.',
                'Production ecrite professionnelle.',
                'Mises en situation et simulations.',
                'Preparation a la certification.',
            ],
        ],
        [
            'slug' => 'anglais-professionnel',
            'title' => 'Anglais professionnel',
            'category' => 'Anglais',
            'summary' => 'Developper son aisance en anglais dans les situations professionnelles courantes.',
            'duration' => 'Parcours modulable',
            'level' => 'A1 a C1 selon positionnement',
            'price' => 'Sur devis',
            'certification' => 'Certification a definir selon objectif',
            'location' => 'Paris, entreprise ou distanciel',
            'format' => 'Presentiel, distanciel ou hybride',
            'funding' => 'CPF, OPCO, entreprise ou particulier selon eligibilite',
            'objectives' => [
                'Gagner en aisance a l oral.',
                'Communiquer par e-mail et en reunion.',
                'Renforcer le vocabulaire professionnel.',
                'Preparer une certification adaptee.',
            ],
            'audience' => 'Professionnels, equipes et particuliers.',
            'requirements' => 'Test de positionnement.',
            'access' => 'Demarrage apres analyse du besoin.',
            'accessibility' => 'Adaptations possibles apres etude.',
            'program' => [
                'Positionnement et objectifs.',
                'Communication orale.',
                'Anglais ecrit professionnel.',
                'Mises en situation metier.',
                'Preparation certification.',
            ],
        ],
        [
            'slug' => 'preparation-tef',
            'title' => 'Preparation TEF',
            'category' => 'Examens',
            'summary' => 'Parcours de preparation aux epreuves du TEF avec diagnostic et entrainement cible.',
            'duration' => 'Parcours court ou intensif',
            'level' => 'Selon objectif',
            'price' => 'Sur devis',
            'certification' => 'TEF',
            'location' => 'Paris ou distanciel',
            'format' => 'Coaching, ateliers ou parcours individuel',
            'funding' => 'Selon profil et objectif',
            'objectives' => [
                'Comprendre la structure des epreuves.',
                'S entrainer sur les competences evaluees.',
                'Identifier les axes de progression.',
                'Se presenter avec une strategie claire.',
            ],
            'audience' => 'Candidats TEF pour projet personnel, professionnel ou administratif.',
            'requirements' => 'Objectif de score a preciser.',
            'access' => 'Sur calendrier de sessions.',
            'accessibility' => 'Besoins particuliers a signaler avant inscription.',
            'program' => [
                'Diagnostic initial.',
                'Methodologie des epreuves.',
                'Entrainements chronometres.',
                'Correction et plan d action.',
            ],
        ],
    ],
    'exam_sessions' => [
        [
            'id' => 'tef-session-info',
            'exam' => 'TEF',
            'date' => 'Dates a venir',
            'time' => 'A confirmer',
            'location' => '26-28 rue de Londres, 75009 Paris',
            'seats' => 'Places limitees',
            'price' => 'Tarif a confirmer',
        ],
    ],
    'articles' => [
        [
            'slug' => 'bien-preparer-son-projet-de-formation',
            'title' => 'Bien preparer son projet de formation linguistique',
            'date' => '2026-05-09',
            'excerpt' => 'Les points a clarifier avant de demander un devis : niveau, objectif, financement, calendrier et certification.',
            'content' => [
                'Un projet de formation solide commence par un objectif clair : progresser pour son poste, obtenir une certification, preparer une mobilite ou accompagner une equipe.',
                'ARCS aide a formaliser le besoin, evaluer le niveau initial et identifier le financement adapte.',
            ],
        ],
    ],
];
